version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme
sphinx:
    configuration: docs/conf.py

python:
  install:
      - path: . 
